name: Archive Gluon Sites
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update Submodules
        run: |
          git submodule update --remote
      - name: git status; git diff
        run: |
          git status
          git diff
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
